title: "Departamento de Informática - EEST N°4"
description: "Noticias, proyectos y actividades del Departamento de Informática"
url: "https://mundoinfoeestn4.github.io/pagina-informatica-jekyll"
remote_theme: "jekyll/minima@1e8a445"
markdown: kramdown
plugins:
  - jekyll-feed
